# Generated by Django 3.0.4 on 2020-03-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_data',
            new_name='added_date',
        ),
    ]
