# Generated by Django 3.0.4 on 2020-03-23 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20200323_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 10, 26, 56, 461543, tzinfo=utc)),
        ),
    ]
